# Generated by Django 6.0.7 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
