# Generated by Django 6.0.7 on 2026-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
